name: Generate PlantUML Diagrams

on:
  push:
    paths:
      - '**.puml'
  pull_request:
    paths:
      - '**.puml'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      puml_files: ${{ steps.getfile.outputs.files }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Get list of .puml files
      id: getfile
      run: |
        echo "files=$(find . -path './**/*.puml'| jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Generate PlantUML diagrams
      uses: docker://ghcr.io/kcirtapfromspace/plantuml/plantuml:latest
      with:
        args: -v -tsvg -tpng ${{ fromJson(needs.prepare.outputs.puml_files) }}

    - name: Push Local Changes
      uses:  stefanzweifel/git-auto-commit-action@v4.16.0 
      with: 
        commit_user_name: "GitHub Actions"
        commit_user_email: "github-actions@users.noreply.github.com"
        commit_author: "Generate PlantUML Diagrams <github-actions@users.noreply.github.com>"
        commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
        branch: ${{ github.head_ref }}

    # - name: Set up Git user
    #   run: |
    #     git config --local user.email "github-actions@users.noreply.github.com"
    #     git config --local user.name "GitHub Actions"

    # - name: Commit generated diagrams
    #   run: |
    #     png_file="$(echo '${{ matrix.puml_file }}' | sed 's/\.puml$/.png/')"
    #     svg_file="$(echo '${{ matrix.puml_file }}' | sed 's/\.puml$/.svg/')"
    #     git add $png_file
    #     git diff-index --quiet HEAD || git commit -m "Update generated PlantUML diagrams"
    #     git push origin ${{ github.head_ref }}
