name: Generate PlantUML diagrams

on:
  push:
    paths:
      - '**.puml'
  pull_request:
    paths:
      - '**.puml'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      puml_files: ${{ steps.getfile.outputs.files }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Get list of .puml files
      id: getfile
      run: |
        echo "files=$(find . -path './**/*.puml'| jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  generate-diagrams:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        puml_file: ${{ fromJson(needs.prepare.outputs.puml_files) }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Generate PlantUML diagrams
      uses: docker://ghcr.io/kcirtapfromspace/plantuml/plantuml:latest
      with:
        args: -v -tsvg -tpng ${{ matrix.puml_file }}

    - name: Set up Git user
      run: |
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "GitHub Actions"

    - name: Commit generated diagrams
      run: |
        png_file="${{ replace(matrix.puml_file, '.puml', '.png') }}"
        git add $png_file
        git diff-index --quiet HEAD || git commit -m "Update generated PlantUML diagrams"
        git push origin ${{ github.head_ref }}