name: Generate PlantUML diagrams

on:
  push:
    paths:
      - 'doc/design/**'
  pull_request:
    paths:
      - 'doc/design/**'

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Check for deleted files
      id: check-deleted
      run: |
        DELETED_FILES=$(git diff --diff-filter=D --name-only HEAD^ HEAD | grep 'doc/design/')
        if [ -n "$DELETED_FILES" ]; then
          echo "::set-output name=skip::true"
        else
          echo "::set-output name=skip::false"
        fi
      shell: bash

    - name: Generate PlantUML diagrams
      if: steps.check-deleted.outputs.skip == 'false'
      run: |
        docker run --rm -v ${{ github.workspace }}/doc/design/assets:/assets ghcr.io/kcirtapfromspace/plantuml/plantuml:latest

    - name: Set up Git user
      if: steps.check-deleted.outputs.skip == 'false'
      run: |
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "GitHub Actions"

    - name: Commit generated diagrams
      if: steps.check-deleted.outputs.skip == 'false'
      run: |
        git add doc/design/assets
        git diff-index --quiet HEAD || git commit -m "Update generated PlantUML diagrams"
        git push origin ${{ github.head_ref }}
